### ISSUE TITLE
"doesn't know its parents" error message — need to use gitlab-grit

### ISSUE THREAD

**Issue by ruv** [jerith666/git-graph#9]
This tools doesn't work in default installation (at least on Cygwin). It just produces 
`#omitting #xxx that doesn't know its parents`
for every item.

The command `gem install gitlab-grit` solves this problem. It installs [GitLab fork of Grit](https://rubygems.org/gems/gitlab-grit/) version 2.8.1 (for the moment).

Whereas by default Grit 2.5.0 is installed. But it seems that this version is outdated now and [Grit is no longer maintained](https://github.com/mojombo/grit).

In default installation, `ref.parents` throws NoMethodError on every item [in filtering](https://github.com/jerith666/git-graph/blob/26a98d9d0621eb3a1ed88d10d97977a30de12465/git-graph.rb#L288
) `decorated` list:
```
decorated.reject!{|ref|
begin
  ref.parents
  false
rescue NoMethodError
  puts "#omitting #{ref} that doesn't know its parents"
  true
end}

```

Actually, `repo.branches[0].commit.parents` throws error:
```
NoMethodError: undefined method `>>' for "x":String
```

**Comment by jerith666** [comment]
Seems like a common theme -- see #7 and #8 as well.  :)

Shall we just patch `README` to say to install https://github.com/gitlabhq/grit explicitly?

**Comment by ruv** [comment]
Yes, patching `README` is better than nothing ;)

But why don't just update [Gemfile](/jerith666/git-graph/blob/master/Gemfile) — can we put `gem "gitlab-grit"` in place of `gem "grit"`?

**Comment by jerith666** [comment]
Duh, yes -- sorry, I'm not doing much ruby these days.  :)  PR welcome, otherwise I'll try to get it done myself soon.
